/**
 * Ngân hàng câu hỏi ngữ pháp soạn tay – bổ sung cho bộ sinh tự động (gen.js).
 * Mỗi câu: [mức 1|2|3, câu hỏi (___ = chỗ trống), đáp án, [3 đáp án nhiễu], giải thích, [cách viết khác được chấp nhận], loại]
 *   loại: bỏ trống = điền/chọn dạng động từ · 'pick' = chọn câu đúng (chỉ trắc nghiệm)
 * Mức 1 cơ bản · 2 khó · 3 siêu khó (phân biệt thì trong câu phức, bẫy hay gặp).
 */
const B = {
  ps: [
    [1, 'My mother ___ (cook) dinner every evening.', 'cooks', ['cook', 'is cooking', 'cooked'], 'Thói quen hằng ngày + chủ ngữ ngôi 3 số ít → V-s.'],
    [1, 'Water ___ (boil) at 100 degrees Celsius.', 'boils', ['boil', 'is boiling', 'boiled'], 'Sự thật hiển nhiên → Hiện tại đơn.'],
    [1, 'We ___ (go) to the cinema on Saturdays.', 'go', ['goes', 'are going', 'went'], 'Chủ ngữ "we" → động từ nguyên mẫu.'],
    [1, 'The train ___ (leave) at 7:30 every morning.', 'leaves', ['leave', 'is leaving', 'left'], 'Lịch trình cố định → Hiện tại đơn.'],
    [1, 'She ___ (be) a doctor.', 'is', ['am', 'are', 'be'], '"She" đi với "is".'],
    [1, 'I ___ (not / like) coffee.', "don't like", ["doesn't like", 'not like', 'am not liking'], 'Phủ định với "I" → do not / don\'t + V.', ['do not like']],
    [1, 'They ___ (be) my best friends.', 'are', ['is', 'am', 'be'], '"They" đi với "are".'],
    [2, '___ (your father / work) in a hospital?', 'Does your father work', ['Do your father work', 'Is your father work', 'Does your father works'], 'Câu hỏi ngôi 3 số ít: Does + S + V nguyên mẫu (không thêm -s).'],
    [2, 'He ___ (not / have) any brothers or sisters.', "doesn't have", ["don't have", "hasn't", "doesn't has"], 'Phủ định: doesn\'t + V nguyên mẫu (have, không phải has).', ['does not have']],
    [2, 'My sister always ___ (try) her best at school.', 'tries', ['trys', 'try', 'is trying'], 'Phụ âm + y → bỏ y thêm -ies.'],
    [2, 'Tom rarely ___ (watch) TV in the morning.', 'watches', ['watchs', 'watch', 'is watching'], 'Động từ tận cùng -ch thêm -es.'],
    [2, 'How often ___ (you / visit) your grandparents?', 'do you visit', ['are you visit', 'do you visits', 'does you visit'], 'Câu hỏi với "you" → do you + V.'],
    [2, 'The meeting ___ (start) at 9 tomorrow, so don\'t be late.', 'starts', ['will start', 'is starting', 'started'], 'Lịch trình / thời gian biểu cố định dùng Hiện tại đơn dù nói về tương lai.'],
    [2, 'Cats ___ (not / eat) vegetables.', "don't eat", ["doesn't eat", 'not eat', "aren't eating"], 'Danh từ số nhiều "cats" → don\'t.', ['do not eat']],
    [3, 'I\'ll call you as soon as I ___ (arrive) at the airport.', 'arrive', ['will arrive', 'am arriving', 'arrived'], 'Mệnh đề thời gian (as soon as / when / until) nói về tương lai dùng Hiện tại đơn, không dùng will.'],
    [3, 'If it ___ (rain) tomorrow, we will stay at home.', 'rains', ['will rain', 'is raining', 'rained'], 'Câu điều kiện loại 1: mệnh đề if dùng Hiện tại đơn.'],
    [3, 'Câu nào đúng ngữ pháp?', 'She doesn\'t know the answer.', ['She don\'t know the answer.', 'She doesn\'t knows the answer.', 'She isn\'t know the answer.'], 'Phủ định ngôi 3 số ít: doesn\'t + V nguyên mẫu.', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'He always goes to bed early.', ['He goes always to bed early.', 'He always go to bed early.', 'Always he goes to bed early.'], 'Trạng từ tần suất đứng trước động từ thường; ngôi 3 số ít thêm -s.', [], 'pick'],
    [3, 'This soup ___ (taste) delicious! Who made it?', 'tastes', ['is tasting', 'has tasted', 'tasted'], '"Taste" ở nghĩa "có vị" là động từ trạng thái → Hiện tại đơn, không dùng tiếp diễn.'],
    [3, 'Nowadays, more and more people ___ (work) from home, but my boss still ___ (prefer) the office.', 'work / prefers', ['are working / is preferring', 'work / prefer', 'works / prefers'], '"people" số nhiều → work; "prefer" là động từ trạng thái, ngôi 3 số ít → prefers.'],
    [3, 'Câu nào đúng ngữ pháp?', 'Does she have a car?', ['Does she has a car?', 'Has she a car?', 'Do she have a car?'], 'Câu hỏi với does → động từ nguyên mẫu "have".', [], 'pick'],
  ],
  pc: [
    [1, 'Look! The baby ___ (sleep).', 'is sleeping', ['sleeps', 'sleep', 'slept'], '"Look!" → hành động đang diễn ra → Hiện tại tiếp diễn.'],
    [1, 'I ___ (read) a very interesting book at the moment.', 'am reading', ['read', 'is reading', 'reads'], '"at the moment" → am/is/are + V-ing; "I" đi với "am".'],
    [1, 'They ___ (play) football in the yard right now.', 'are playing', ['play', 'is playing', 'played'], '"right now" + "they" → are playing.'],
    [1, 'Be quiet! The teacher ___ (talk).', 'is talking', ['talks', 'talk', 'talking'], 'Đang diễn ra lúc nói.'],
    [1, 'We ___ (not / watch) TV now. We ___ (study).', "aren't watching / are studying", ["don't watch / study", "isn't watching / is studying", "not watching / studying"], 'Phủ định: are not + V-ing.', ['are not watching / are studying']],
    [1, '___ (you / listen) to me?', 'Are you listening', ['Do you listen', 'Are you listen', 'You are listening'], 'Câu hỏi: Are + you + V-ing?'],
    [2, 'She ___ (lie) on the beach right now.', 'is lying', ['is lieing', 'is laying', 'lies'], 'lie → lying (ie → y + ing).'],
    [2, 'Why ___ (he / run)? Is he late?', 'is he running', ['is he runing', 'does he run', 'he is running'], 'run → gấp đôi phụ âm: running.'],
    [2, 'My brother ___ (stay) with us this month.', 'is staying', ['stays', 'stay', 'stayed'], 'Hành động tạm thời quanh thời điểm hiện tại → Hiện tại tiếp diễn.'],
    [2, 'We ___ (have) dinner with the Smiths tomorrow evening.', 'are having', ['have', 'has', 'will having'], 'Kế hoạch đã sắp xếp chắc chắn → Hiện tại tiếp diễn mang nghĩa tương lai.'],
    [2, 'He ___ (always / lose) his keys! It\'s so annoying.', 'is always losing', ['always loses', 'always is losing', 'is losing always'], 'Phàn nàn thói quen: be + always + V-ing.'],
    [2, 'I ___ (not / work) today. It\'s my day off.', "am not working", ["don't work", "am not work", "isn't working"], 'Phủ định với "I": am not + V-ing (không rút gọn).'],
    [2, 'The children ___ (get) taller every year.', 'are getting', ['get', 'gets', 'is getting'], 'Sự thay đổi dần dần → Hiện tại tiếp diễn.'],
    [3, 'I ___ (think) you\'re right. – Shh, I ___ (think) about the problem.', 'think / am thinking', ['am thinking / think', 'think / think', 'am thinking / am thinking'], '"think" = cho rằng → trạng thái (HTĐ); "think about" = đang suy nghĩ → hành động (HTTD).'],
    [3, 'Câu nào đúng ngữ pháp?', 'I don\'t understand what he is saying.', ['I\'m not understanding what he is saying.', 'I don\'t understand what he says now.', 'I not understand what he is saying.'], '"understand" là động từ trạng thái → không dùng tiếp diễn; "is saying" đang diễn ra.', [], 'pick'],
    [3, 'She usually ___ (drive) to work, but today she ___ (take) the bus.', 'drives / is taking', ['is driving / takes', 'drives / takes', 'is driving / is taking'], 'Thói quen (usually) → HTĐ; hôm nay khác thường (today) → HTTD.'],
    [3, 'Câu nào đúng ngữ pháp?', 'Are you seeing the doctor tomorrow?', ['Do you see the doctor tomorrow?', 'Are you see the doctor tomorrow?', 'Will you seeing the doctor tomorrow?'], '"see" = gặp (có hẹn) dùng được ở tiếp diễn với nghĩa tương lai đã sắp xếp.', [], 'pick'],
    [3, 'This cake ___ (smell) wonderful. Are you baking again?', 'smells', ['is smelling', 'smell', 'has smelled'], '"smell" = có mùi → động từ trạng thái, dùng Hiện tại đơn.'],
    [3, 'Câu nào đúng ngữ pháp?', 'He\'s always complaining about the weather.', ['He always is complaining about the weather.', 'He\'s complaining always about the weather.', 'He always complaining about the weather.'], 'Cấu trúc phàn nàn: be + always + V-ing.', [], 'pick'],
  ],
  pp: [
    [1, 'I ___ (live) in this city for ten years.', 'have lived', ['lived', 'live', 'am living'], '"for ten years" – kéo dài đến hiện tại → Hiện tại hoàn thành.'],
    [1, 'She ___ (just / finish) her homework.', 'has just finished', ['just finished', 'has finished just', 'is just finishing'], '"just" đứng giữa has và V3.'],
    [1, '___ (you / ever / be) to London?', 'Have you ever been', ['Did you ever be', 'Have you ever gone', 'Were you ever'], 'Trải nghiệm trong đời: Have you ever been to…?'],
    [1, 'They ___ (not / arrive) yet.', "haven't arrived", ["didn't arrive", "hasn't arrived", "haven't arrive"], '"yet" + phủ định → haven\'t + V3.', ['have not arrived']],
    [1, 'We ___ (know) each other since 2015.', 'have known', ['knew', 'know', 'have knew'], '"since 2015" → have + V3 (know → known).'],
    [1, 'He ___ (already / eat) lunch.', 'has already eaten', ['already ate', 'has already ate', 'already has eaten'], '"already" giữa has và V3 (eat → eaten).'],
    [2, 'This is the first time I ___ (see) this film.', 'have seen', ['see', 'saw', 'am seeing'], '"This is the first time" + Hiện tại hoàn thành.'],
    [2, 'My parents ___ (be) married for 30 years.', 'have been', ['are', 'were', 'have being'], 'Trạng thái kéo dài đến nay: have been + for.'],
    [2, 'Tom isn\'t here. He ___ (go) to the supermarket.', 'has gone', ['has been', 'went', 'is gone'], '"has gone to" = đã đi (chưa về); "has been to" = đã từng đến và đã về.'],
    [2, 'I ___ (not / see) Mary lately. Is she OK?', "haven't seen", ["didn't see", "haven't saw", "hasn't seen"], '"lately" → Hiện tại hoàn thành; see → seen.', ['have not seen']],
    [2, 'How many countries ___ (she / visit) so far?', 'has she visited', ['did she visit', 'has she visit', 'have she visited'], '"so far" → HTHT; "she" → has.'],
    [2, 'Anna ___ (write) three emails this morning and it\'s still only 10 a.m.', 'has written', ['wrote', 'has wrote', 'is writing'], '"this morning" chưa kết thúc → HTHT; write → written.'],
    [2, 'I ___ (lose) my phone. Can I borrow yours?', 'have lost', ['lost', 'lose', 'am losing'], 'Kết quả ảnh hưởng đến hiện tại (giờ không có điện thoại) → HTHT.'],
    [3, 'I ___ (see) that movie three times, and I ___ (see) it again last night.', 'have seen / saw', ['saw / have seen', 'have seen / have seen', 'saw / saw'], 'Trải nghiệm không nêu thời điểm → HTHT; "last night" thời điểm xác định → QKĐ.'],
    [3, 'Câu nào đúng ngữ pháp?', 'She has worked here since she graduated.', ['She has worked here since she has graduated.', 'She works here since she graduated.', 'She worked here since she graduated.'], 'Mệnh đề chính HTHT; sau "since" là mốc quá khứ → QKĐ.', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'I have known him for five years.', ['I have known him since five years.', 'I know him for five years.', 'I have been knowing him for five years.'], '"know" trạng thái → HTHT (không tiếp diễn); for + khoảng thời gian.', [], 'pick'],
    [3, 'Shakespeare ___ (write) many plays. J.K. Rowling ___ (write) seven Harry Potter books.', 'wrote / has written', ['has written / wrote', 'has written / has written', 'wrote / wrote'], 'Shakespeare đã mất → QKĐ; Rowling còn sống, có thể viết thêm → HTHT.'],
    [3, 'Câu nào đúng ngữ pháp?', 'Have you finished the report yet?', ['Have you yet finished the report?', 'Did you finish the report yet?', 'Have you already finished the report yet?'], '"yet" đứng cuối câu hỏi / phủ định, không dùng cùng "already".', [], 'pick'],
    [3, 'It\'s the best book I ___ (ever / read).', 'have ever read', ['ever read', 'had ever read', 'ever have read'], 'So sánh nhất + HTHT với "ever".'],
  ],
  ppc: [
    [1, 'I ___ (wait) for you for two hours!', 'have been waiting', ['have waited', 'am waiting', 'waited'], 'Nhấn mạnh quá trình kéo dài đến hiện tại → have been + V-ing.'],
    [1, 'She ___ (study) English since 2020.', 'has been studying', ['has studied', 'is studying', 'studies'], '"since 2020" + nhấn mạnh quá trình → HTHTTD.'],
    [1, 'They ___ (play) tennis all morning.', 'have been playing', ['have played', 'are playing', 'played'], '"all morning" → HTHTTD.'],
    [1, 'How long ___ (you / learn) Japanese?', 'have you been learning', ['do you learn', 'are you learning', 'did you learn'], '"How long" hỏi thời lượng đến hiện tại.'],
    [1, 'We ___ (not / sleep) well lately.', "haven't been sleeping", ["haven't slept", "aren't sleeping", "didn't sleep"], 'Phủ định: haven\'t been + V-ing.', ['have not been sleeping']],
    [1, 'It ___ (rain) since morning.', 'has been raining', ['has rained', 'is raining', 'rains'], '"since morning" – mưa liên tục đến giờ.'],
    [2, 'You look exhausted. ___ (you / run)?', 'Have you been running', ['Did you run', 'Are you running', 'Have you run'], 'Dấu vết ở hiện tại (mệt) của hoạt động vừa diễn ra → HTHTTD.'],
    [2, 'He ___ (work) here for ten years and he still loves it.', 'has been working', ['has worked', 'works', 'is working'], 'Nhấn mạnh quá trình dài liên tục; both OK nhưng "still" → nhấn tiếp diễn.', ['has worked']],
    [2, 'My eyes hurt because I ___ (look) at the screen all day.', 'have been looking', ['looked', 'am looking', 'have looked'], 'Nguyên nhân của tình trạng hiện tại → HTHTTD.'],
    [2, 'The kids are dirty. They ___ (play) in the mud.', 'have been playing', ['played', 'have played', 'are playing'], 'Kết quả rõ ràng ở hiện tại của hành động vừa kết thúc.'],
    [2, 'She ___ (not / feel) well recently, so she went to the doctor.', "hasn't been feeling", ["hasn't felt", "wasn't feeling", "isn't feeling"], '"recently" + quá trình → HTHTTD.', ['has not been feeling']],
    [2, 'How long ___ (it / snow)? The roads are covered.', 'has it been snowing', ['is it snowing', 'does it snow', 'did it snow'], 'Hỏi thời lượng của hành động vẫn đang tiếp diễn.'],
    [3, 'I ___ (write) emails all morning, and I ___ (write) ten so far.', 'have been writing / have written', ['have written / have been writing', 'have been writing / have been writing', 'wrote / have written'], 'Quá trình → HTHTTD; kết quả đếm được (ten) → HTHT.'],
    [3, 'Câu nào đúng ngữ pháp?', 'I have known her since we were children.', ['I have been knowing her since we were children.', 'I have been known her since we were children.', 'I am knowing her since we were children.'], '"know" trạng thái → không dùng dạng tiếp diễn.', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'She has been living in Paris for three years.', ['She is living in Paris for three years.', 'She lives in Paris since three years.', 'She has been lived in Paris for three years.'], 'have/has + been + V-ing; for + khoảng thời gian.', [], 'pick'],
    [3, 'Somebody ___ (eat) my chocolate! There\'s only one piece left.', 'has been eating', ['has eaten', 'ate', 'is eating'], 'Hành động chưa xong (còn một miếng) → HTHTTD; "has eaten" ngụ ý ăn hết.'],
    [3, 'By the look of it, they ___ (argue) again. Both of them are red in the face.', 'have been arguing', ['argue', 'have argued', 'had been arguing'], 'Bằng chứng hiện tại (mặt đỏ) → HTHTTD.'],
    [3, 'Câu nào đúng ngữ pháp?', 'How long have you been waiting here?', ['How long are you waiting here?', 'How long have you waiting here?', 'How long do you wait here?'], 'Hỏi thời lượng đến hiện tại → HTHTTD.', [], 'pick'],
  ],
  pas: [
    [1, 'I ___ (visit) my grandmother last weekend.', 'visited', ['visit', 'have visited', 'was visiting'], '"last weekend" → Quá khứ đơn.'],
    [1, 'She ___ (go) to Paris in 2019.', 'went', ['goed', 'has gone', 'goes'], 'go → went (bất quy tắc).'],
    [1, 'They ___ (not / come) to the party yesterday.', "didn't come", ["didn't came", "don't come", "haven't come"], 'Phủ định: didn\'t + V nguyên mẫu.', ['did not come']],
    [1, '___ (you / watch) the match last night?', 'Did you watch', ['Did you watched', 'Do you watch', 'Have you watched'], 'Câu hỏi: Did + S + V nguyên mẫu?'],
    [1, 'We ___ (be) very happy yesterday.', 'were', ['was', 'are', 'been'], '"We" → were.'],
    [1, 'He ___ (stop) the car and ___ (get) out.', 'stopped / got', ['stoped / got', 'stopped / getted', 'stops / gets'], 'stop → stopped (gấp đôi p); get → got.'],
    [2, 'The Second World War ___ (end) in 1945.', 'ended', ['has ended', 'was ending', 'had ended'], 'Sự kiện lịch sử có thời điểm xác định → QKĐ.'],
    [2, 'Where ___ (you / be) at 8 o\'clock last night?', 'were you', ['was you', 'did you be', 'have you been'], 'Câu hỏi với "be": Were + you…?'],
    [2, 'I ___ (not / be) hungry, so I ___ (not / eat) anything.', "wasn't / didn't eat", ["didn't be / didn't eat", "wasn't / didn't ate", "weren't / didn't eat"], 'Phủ định của be: wasn\'t; động từ thường: didn\'t + V.', ['was not / did not eat']],
    [2, 'She ___ (teach) at that school for five years before she retired.', 'taught', ['teached', 'has taught', 'was teaching'], 'Khoảng thời gian đã kết thúc hoàn toàn (đã nghỉ hưu) → QKĐ; teach → taught.'],
    [2, 'When I was a child, I ___ (play) outside every day.', 'played', ['have played', 'was playing', 'play'], 'Thói quen trong quá khứ → QKĐ (hoặc used to).'],
    [2, 'Who ___ (break) the window?', 'broke', ['did break', 'breaked', 'has broke'], 'Câu hỏi với "who" làm chủ ngữ → không dùng did; break → broke.'],
    [2, 'My brother ___ (buy) a new laptop two days ago.', 'bought', ['buyed', 'has bought', 'buys'], '"ago" → QKĐ; buy → bought.'],
    [3, 'I ___ (live) in Hanoi for five years, but now I live in Da Nang.', 'lived', ['have lived', 'had lived', 'was living'], 'Khoảng thời gian đã kết thúc (giờ ở nơi khác) → QKĐ, không phải HTHT.'],
    [3, 'Câu nào đúng ngữ pháp?', 'When did you arrive in Vietnam?', ['When have you arrived in Vietnam?', 'When did you arrived in Vietnam?', 'When you arrived in Vietnam?'], '"When" hỏi thời điểm cụ thể → QKĐ, did + V nguyên mẫu.', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'I didn\'t see him yesterday.', ['I haven\'t seen him yesterday.', 'I didn\'t saw him yesterday.', 'I not saw him yesterday.'], '"yesterday" → QKĐ; sau didn\'t là nguyên mẫu.', [], 'pick'],
    [3, 'She ___ (be) to Japan twice. The last time she ___ (go) there was in 2022.', 'has been / went', ['went / has gone', 'was / went', 'has been / has gone'], 'Trải nghiệm → HTHT; thời điểm cụ thể (2022) → QKĐ.'],
    [3, 'As soon as the bell ___ (ring), the students ___ (run) out of the classroom.', 'rang / ran', ['was ringing / ran', 'rang / were running', 'had rung / ran'], 'Hai hành động nối tiếp trong quá khứ → cả hai QKĐ.'],
    [3, 'Câu nào đúng ngữ pháp?', 'The film was so boring that we left early.', ['The film was so boring that we leaved early.', 'The film has been so boring that we left early.', 'The film was so boring that we have left early.'], 'leave → left (bất quy tắc); cả hai vế đều QKĐ.', [], 'pick'],
  ],
  pac: [
    [1, 'At 9 o\'clock last night, I ___ (do) my homework.', 'was doing', ['did', 'am doing', 'were doing'], 'Thời điểm cụ thể trong quá khứ + đang diễn ra → was/were + V-ing.'],
    [1, 'They ___ (play) football when it started to rain.', 'were playing', ['played', 'was playing', 'are playing'], 'Hành động dài (QKTD) bị hành động ngắn xen vào (QKĐ).'],
    [1, 'What ___ (you / do) at this time yesterday?', 'were you doing', ['did you do', 'was you doing', 'are you doing'], '"at this time yesterday" → QKTD.'],
    [1, 'She ___ (not / listen) to the teacher.', "wasn't listening", ["didn't listen", "weren't listening", "isn't listening"], 'Phủ định: was not + V-ing.', ['was not listening']],
    [1, 'The sun ___ (shine) and the birds ___ (sing).', 'was shining / were singing', ['shone / sang', 'were shining / was singing', 'is shining / are singing'], 'Tả cảnh nền trong quá khứ → QKTD.'],
    [1, 'I ___ (sleep) when the phone rang.', 'was sleeping', ['slept', 'were sleeping', 'am sleeping'], 'Đang ngủ (dài) thì chuông reo (ngắn).'],
    [2, 'While I ___ (cook), my husband ___ (set) the table.', 'was cooking / was setting', ['cooked / set', 'was cooking / set', 'cooked / was setting'], 'Hai hành động song song → cả hai QKTD.'],
    [2, 'He ___ (drive) too fast, so the police stopped him.', 'was driving', ['drove', 'had driven', 'drives'], 'Hành động đang diễn ra làm nền cho sự việc xảy ra.'],
    [2, '___ (it / rain) when you left the office?', 'Was it raining', ['Did it rain', 'Were it raining', 'Is it raining'], 'Câu hỏi: Was + it + V-ing?'],
    [2, 'When I saw Tom, he ___ (wear) a strange hat.', 'was wearing', ['wore', 'wears', 'had worn'], 'Tình trạng đang diễn ra tại thời điểm nhìn thấy.'],
    [2, 'We ___ (not / expect) any visitors, so we were surprised.', "weren't expecting", ["didn't expect", "wasn't expecting", "hadn't expected"], 'Trạng thái đang diễn ra trong quá khứ; "we" → weren\'t.', ['were not expecting']],
    [2, 'The students ___ (talk) loudly when the teacher walked in.', 'were talking', ['talked', 'was talking', 'have talked'], '"when + QKĐ" xen vào hành động đang diễn ra.'],
    [3, 'When the teacher came in, the students ___ (stop) talking and ___ (sit) down.', 'stopped / sat', ['were stopping / were sitting', 'stopped / were sitting', 'had stopped / sat'], 'Hành động xảy ra ngay sau hành động "when" → chuỗi hành động QKĐ, không phải đang diễn ra.'],
    [3, 'Câu nào đúng ngữ pháp?', 'I was having lunch when she called.', ['I had lunch when she was calling.', 'I was having lunch when she was calling.', 'I have had lunch when she called.'], 'Hành động dài đang diễn ra (QKTD) + hành động ngắn xen vào (QKĐ).', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'She didn\'t know the answer, so she kept quiet.', ['She wasn\'t knowing the answer, so she kept quiet.', 'She wasn\'t knowing the answer, so she was keeping quiet.', 'She didn\'t knew the answer, so she kept quiet.'], '"know" trạng thái → không dùng QKTD.', [], 'pick'],
    [3, 'I ___ (walk) home last night when I suddenly ___ (realise) I ___ (not / have) my wallet.', "was walking / realised / didn't have", ['walked / was realising / had not', "was walking / realised / wasn't having", 'walked / realised / had not had'], 'Nền dài → QKTD; hành động ngắn → QKĐ; "have" sở hữu → không tiếp diễn.', ["was walking / realized / didn't have", 'was walking / realised / did not have']],
    [3, 'Câu nào đúng ngữ pháp?', 'While we were driving to the coast, the car broke down.', ['While we drove to the coast, the car was breaking down.', 'While we were driving to the coast, the car was breaking down.', 'While we drove to the coast, the car broke down.'], '"while" + hành động dài (QKTD); sự cố ngắn → QKĐ.', [], 'pick'],
    [3, 'At the time of the accident, the driver ___ (talk) on his phone and ___ (not / pay) attention.', "was talking / wasn't paying", ["talked / didn't pay", "was talking / didn't pay", "talked / wasn't paying"], 'Cả hai hành động đang diễn ra tại thời điểm tai nạn.', ['was talking / was not paying']],
  ],
  pap: [
    [1, 'When I arrived at the station, the train ___ (already / leave).', 'had already left', ['already left', 'has already left', 'was already leaving'], 'Hành động xảy ra trước hành động "arrived" (QKĐ) → QKHT.'],
    [1, 'She ___ (finish) her homework before dinner.', 'had finished', ['finished', 'has finished', 'was finishing'], 'Xảy ra trước một mốc trong quá khứ (dinner).'],
    [1, 'By 2015, they ___ (move) to a new house.', 'had moved', ['moved', 'have moved', 'were moving'], '"By + mốc quá khứ" → QKHT.'],
    [1, 'He ___ (never / see) the sea before that trip.', 'had never seen', ['never saw', 'has never seen', 'never had seen'], '"never… before + mốc quá khứ" → QKHT.'],
    [1, 'I ___ (not / eat) anything all day, so I was very hungry.', "hadn't eaten", ["didn't eat", "haven't eaten", "wasn't eating"], 'Phủ định: hadn\'t + V3.', ['had not eaten']],
    [1, '___ (you / meet) him before the party?', 'Had you met', ['Did you meet', 'Have you met', 'Had you meet'], 'Câu hỏi: Had + S + V3?'],
    [2, 'The house was dirty because nobody ___ (clean) it for weeks.', 'had cleaned', ['cleaned', 'has cleaned', 'was cleaning'], 'Nguyên nhân xảy ra trước tình trạng quá khứ → QKHT.'],
    [2, 'She told me she ___ (lose) her passport.', 'had lost', ['lost', 'has lost', 'loses'], 'Câu gián tiếp: QKĐ "told" → hành động trước đó lùi về QKHT.'],
    [2, 'By the time we got to the cinema, the film ___ (start).', 'had started', ['started', 'has started', 'was starting'], '"By the time + QKĐ" → mệnh đề chính QKHT.'],
    [2, 'I didn\'t recognise him because he ___ (change) so much.', 'had changed', ['changed', 'has changed', 'was changing'], 'Thay đổi diễn ra trước lúc gặp.'],
    [2, 'After they ___ (eat) dinner, they went for a walk.', 'had eaten', ['ate', 'have eaten', 'were eating'], '"After + QKHT, QKĐ".', ['ate']],
    [2, 'It was the first time she ___ (drive) a car.', 'had driven', ['drove', 'has driven', 'had drove'], '"It was the first time" (quá khứ) + QKHT.'],
    [3, 'When I ___ (get) home, my wife ___ (already / cook) dinner, so we ___ (eat) right away.', 'got / had already cooked / ate', ['had got / already cooked / ate', 'got / already cooked / had eaten', 'got / had already cooked / had eaten'], 'Mốc QKĐ (got); hành động trước → QKHT; hành động sau → QKĐ.'],
    [3, 'Câu nào đúng ngữ pháp?', 'If I had known about the meeting, I would have come.', ['If I knew about the meeting, I would have come.', 'If I had known about the meeting, I would come.', 'If I have known about the meeting, I would have come.'], 'Điều kiện loại 3: If + QKHT, would have + V3.', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'She had left before I arrived.', ['She had left before I had arrived.', 'She left before I had arrived.', 'She has left before I arrived.'], 'Hành động trước → QKHT; hành động sau (mốc) → QKĐ.', [], 'pick'],
    [3, 'I wish I ___ (study) harder when I was at school.', 'had studied', ['studied', 'have studied', 'would study'], 'Ước về quá khứ: wish + QKHT.'],
    [3, 'He ___ (just / sit) down when the phone ___ (ring).', 'had just sat / rang', ['just sat / had rung', 'just sat / rang', 'had just sat / had rung'], 'Ngồi xuống trước → QKHT; chuông reo sau → QKĐ.'],
    [3, 'Câu nào đúng ngữ pháp?', 'By the time the ambulance arrived, the man had died.', ['By the time the ambulance had arrived, the man died.', 'By the time the ambulance arrived, the man has died.', 'By the time the ambulance was arriving, the man had died.'], 'By the time + QKĐ, mệnh đề chính QKHT.', [], 'pick'],
  ],
  papc: [
    [1, 'I ___ (wait) for an hour when the bus finally came.', 'had been waiting', ['was waiting', 'have been waiting', 'waited'], 'Đợi liên tục cho đến khi xe đến (QKĐ) → QKHTTD.'],
    [1, 'She was tired because she ___ (work) all day.', 'had been working', ['worked', 'has been working', 'was working'], 'Nguyên nhân kéo dài trước tình trạng quá khứ.'],
    [1, 'They ___ (live) in London for ten years before they moved to Hanoi.', 'had been living', ['lived', 'have been living', 'were living'], '"for ten years before + QKĐ" → QKHTTD.'],
    [1, 'How long ___ (you / study) English before you took the exam?', 'had you been studying', ['did you study', 'have you been studying', 'were you studying'], 'Hỏi thời lượng trước một mốc quá khứ.'],
    [1, 'It ___ (rain) for days, so the roads were flooded.', 'had been raining', ['rained', 'has been raining', 'was raining'], 'Mưa nhiều ngày trước đó → hậu quả (ngập).'],
    [1, 'He ___ (not / sleep) well, so he looked terrible.', "hadn't been sleeping", ["didn't sleep", "hasn't been sleeping", "wasn't sleeping"], 'Phủ định: hadn\'t been + V-ing.', ['had not been sleeping']],
    [2, 'Her eyes were red. She ___ (cry).', 'had been crying', ['cried', 'has been crying', 'was crying'], 'Dấu vết (mắt đỏ) của hành động vừa diễn ra trước đó.'],
    [2, 'By the time the boss arrived, we ___ (discuss) the problem for two hours.', 'had been discussing', ['discussed', 'have been discussing', 'were discussing'], '"By the time + QKĐ" + for → QKHTTD.'],
    [2, 'The children ___ (play) in the garden, so their clothes were muddy.', 'had been playing', ['played', 'have been playing', 'were playing'], 'Nguyên nhân xảy ra trước hậu quả trong quá khứ.'],
    [2, 'When I met him, he ___ (look) for a job for six months.', 'had been looking', ['looked', 'has been looking', 'was looking'], 'Quá trình kéo dài đến thời điểm gặp (QKĐ).'],
    [2, '___ (she / wait) long before the doctor saw her?', 'Had she been waiting', ['Did she wait', 'Has she been waiting', 'Was she waiting'], 'Câu hỏi: Had + S + been + V-ing?'],
    [2, 'We ___ (drive) for hours when we realised we were lost.', 'had been driving', ['drove', 'have been driving', 'were driving'], '"for hours" trước "realised" (QKĐ).'],
    [3, 'He ___ (write) the report for three hours and he ___ (write) only two pages when the computer crashed.', 'had been writing / had written', ['had written / had been writing', 'was writing / wrote', 'had been writing / had been writing'], 'Quá trình → QKHTTD; kết quả đếm được (two pages) → QKHT.'],
    [3, 'Câu nào đúng ngữ pháp?', 'I had known her for years before we got married.', ['I had been knowing her for years before we got married.', 'I have known her for years before we got married.', 'I knew her for years before we had got married.'], '"know" trạng thái → QKHT, không tiếp diễn.', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'She had been studying all night, so she fell asleep in class.', ['She has been studying all night, so she fell asleep in class.', 'She had been studying all night, so she had fallen asleep in class.', 'She was studying all night, so she fell asleep in class.'], 'Quá trình trước → QKHTTD; hậu quả sau → QKĐ.', [], 'pick'],
    [3, 'The ground was wet. It ___ (rain), but it ___ (stop) by the time we left.', 'had been raining / had stopped', ['rained / stopped', 'had been raining / stopped', 'was raining / had stopped'], 'Mưa (quá trình) và tạnh (hoàn tất) đều trước mốc "left".'],
    [3, 'By the time she retired, she ___ (teach) for 40 years and ___ (help) thousands of students.', 'had been teaching / had helped', ['taught / helped', 'had been teaching / had been helping', 'was teaching / helped'], 'Thời lượng → QKHTTD; kết quả (thousands) → QKHT.'],
    [3, 'Câu nào đúng ngữ pháp?', 'How long had you been living there when the earthquake struck?', ['How long have you been living there when the earthquake struck?', 'How long were you living there when the earthquake had struck?', 'How long had you living there when the earthquake struck?'], 'Hỏi thời lượng trước mốc quá khứ (QKĐ "struck").', [], 'pick'],
  ],
  fs: [
    [1, 'I think it ___ (rain) tomorrow.', 'will rain', ['rains', 'is raining', 'is going to rain'], '"I think" – dự đoán chủ quan → will.'],
    [1, 'Don\'t worry, I ___ (help) you.', 'will help', ['help', 'am helping', 'helped'], 'Lời hứa / đề nghị → will.'],
    [1, 'She ___ (be) 18 next month.', 'will be', ['is', 'is being', 'was'], 'Sự việc chắc chắn trong tương lai.'],
    [1, 'They ___ (not / come) to the party.', "won't come", ["don't come", "aren't come", "won't to come"], 'Phủ định: will not / won\'t + V.', ['will not come']],
    [1, '___ (you / open) the window, please?', 'Will you open', ['Do you open', 'Are you open', 'Will you opening'], 'Yêu cầu lịch sự: Will you…?'],
    [1, 'It\'s hot in here. I ___ (turn) on the fan.', 'will turn', ['turn', 'am turning', 'turned'], 'Quyết định ngay lúc nói → will.'],
    [2, 'A: The phone is ringing. B: I ___ (get) it!', 'will get', ['am going to get', 'get', 'am getting'], 'Quyết định tức thời khi nghe chuông → will (không phải be going to).'],
    [2, 'I promise I ___ (not / tell) anyone your secret.', "won't tell", ["don't tell", "am not telling", "not tell"], 'Lời hứa → won\'t.', ['will not tell']],
    [2, 'Perhaps we ___ (see) each other again someday.', 'will see', ['see', 'are seeing', 'have seen'], '"Perhaps / maybe" → dự đoán không chắc → will.'],
    [2, 'In 2050, people ___ (live) on Mars, I believe.', 'will live', ['live', 'are living', 'lived'], 'Dự đoán về tương lai xa.'],
    [2, 'Wait a minute. I ___ (carry) that bag for you.', 'will carry', ['carry', 'am going to carry', 'carried'], 'Đề nghị giúp đỡ tức thời → will.'],
    [2, 'Who do you think ___ (win) the election?', 'will win', ['wins', 'is winning', 'won'], 'Dự đoán → will.'],
    [3, 'I ___ (call) you when I ___ (get) home.', 'will call / get', ['call / will get', 'will call / will get', 'am calling / get'], 'Mệnh đề chính will; mệnh đề thời gian "when" dùng Hiện tại đơn.'],
    [3, 'Câu nào đúng ngữ pháp?', 'If you study hard, you will pass the exam.', ['If you will study hard, you will pass the exam.', 'If you study hard, you pass the exam.', 'If you studied hard, you will pass the exam.'], 'Điều kiện loại 1: If + HTĐ, will + V.', [], 'pick'],
    [3, 'A: I\'ve already bought the tickets. B: Oh great! So we ___ (go) to the concert after all.', 'are going to go', ['will go', 'go', 'will be going'], 'Kế hoạch đã sắp xếp (đã mua vé) → be going to.', ['are going']],
    [3, 'Câu nào đúng ngữ pháp?', 'I\'ll wait here until she comes back.', ['I\'ll wait here until she will come back.', 'I wait here until she will come back.', 'I\'ll wait here until she is coming back.'], 'Sau "until" dùng Hiện tại đơn, không dùng will.', [], 'pick'],
    [3, 'Look at those dark clouds! It ___ (rain).', 'is going to rain', ['will rain', 'rains', 'is raining'], 'Dự đoán dựa trên bằng chứng nhìn thấy → be going to.'],
    [3, 'Câu nào đúng ngữ pháp?', 'Shall we go for a walk?', ['Will we go for a walk?', 'Shall we going for a walk?', 'Do we shall go for a walk?'], 'Đề nghị với "we" → Shall we…?', [], 'pick'],
  ],
  fc: [
    [1, 'This time tomorrow, I ___ (fly) to Tokyo.', 'will be flying', ['will fly', 'am flying', 'fly'], '"This time tomorrow" → will be + V-ing.'],
    [1, 'At 8 p.m. tonight, we ___ (watch) the final.', 'will be watching', ['will watch', 'watch', 'are watching'], 'Thời điểm cụ thể trong tương lai.'],
    [1, 'Don\'t call me at 7. I ___ (have) dinner.', 'will be having', ['will have', 'have', 'am having'], 'Đang diễn ra tại thời điểm tương lai.'],
    [1, 'She ___ (not / work) tomorrow, it\'s her day off.', "won't be working", ["won't work", "isn't working", "doesn't work"], 'Phủ định: won\'t be + V-ing.', ['will not be working']],
    [1, '___ (you / use) the car this evening?', 'Will you be using', ['Will you use', 'Do you use', 'Are you use'], 'Hỏi lịch sự về dự định: Will you be + V-ing?'],
    [1, 'Next week at this time, they ___ (lie) on a beach in Bali.', 'will be lying', ['will lie', 'lie', 'are lying'], 'lie → lying.'],
    [2, 'By the time you read this, I ___ (travel) somewhere in Europe.', 'will be travelling', ['will travel', 'travel', 'am travelling'], 'Hành động sẽ đang diễn ra khi hành động khác xảy ra.', ['will be traveling']],
    [2, 'The students ___ (take) their exams all next week.', 'will be taking', ['will take', 'take', 'are taking'], '"all next week" – kéo dài → TLTD.'],
    [2, 'I ___ (see) Mr. Lee at the meeting on Monday, so I can give him your message.', 'will be seeing', ['see', 'will have seen', 'saw'], 'Việc chắc chắn theo lịch thông lệ → will be + V-ing.'],
    [2, 'Tomorrow at noon, the president ___ (give) a speech.', 'will be giving', ['gives', 'will have given', 'is giving'], 'Thời điểm cụ thể (tomorrow at noon).'],
    [2, 'What ___ (you / do) at 10 o\'clock tomorrow morning?', 'will you be doing', ['will you do', 'do you do', 'are you do'], 'Hỏi hành động đang diễn ra tại thời điểm tương lai.'],
    [2, 'In a few years, everyone ___ (drive) electric cars.', 'will be driving', ['drives', 'is driving', 'drove'], 'Xu hướng sẽ đang diễn ra trong tương lai.'],
    [3, 'When you arrive, I ___ (wait) for you at the gate, so don\'t worry.', 'will be waiting', ['will wait', 'wait', 'am waiting'], 'Đang diễn ra khi hành động khác xảy ra (when + HTĐ).'],
    [3, 'Câu nào đúng ngữ pháp?', 'I\'ll be working when you call, so leave a message.', ['I\'ll be working when you\'ll call, so leave a message.', 'I\'ll work when you call, so leave a message.', 'I\'m working when you will call, so leave a message.'], 'Mệnh đề thời gian HTĐ; sẽ đang làm việc → will be + V-ing.', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'This time next year, I will be living in Australia.', ['This time next year, I will living in Australia.', 'This time next year, I will be live in Australia.', 'This time next year, I am living in Australia.'], 'will be + V-ing.', [], 'pick'],
    [3, 'I ___ (know) the results by tomorrow, so I ___ (call) you then.', 'will know / will call', ['will be knowing / will be calling', 'know / will call', 'will know / will be calling'], '"know" trạng thái → không tiếp diễn; gọi điện là quyết định / lời hứa → will.'],
    [3, 'Câu nào đúng ngữ pháp?', 'Will you be staying long? – No, just two nights.', ['Will you staying long? – No, just two nights.', 'Do you be staying long? – No, just two nights.', 'Are you will stay long? – No, just two nights.'], 'Will + S + be + V-ing?', [], 'pick'],
    [3, 'Don\'t phone between 8 and 9 – we ___ (have) a meeting, and by 9 it ___ (finish).', 'will be having / will have finished', ['will have / will finish', 'will be having / will be finishing', 'have / will have finished'], 'Đang diễn ra trong khoảng thời gian → TLTD; hoàn tất trước 9 giờ → TLHT.'],
  ],
  fp: [
    [1, 'By next June, I ___ (graduate).', 'will have graduated', ['will graduate', 'graduate', 'have graduated'], '"By + mốc tương lai" → will have + V3.'],
    [1, 'She ___ (finish) the report by 5 p.m.', 'will have finished', ['will finish', 'finishes', 'has finished'], 'Hoàn thành trước 5 giờ chiều.'],
    [1, 'By the time you get here, we ___ (eat) dinner.', 'will have eaten', ['will eat', 'eat', 'have eaten'], '"By the time + HTĐ" → mệnh đề chính TLHT.'],
    [1, 'They ___ (not / build) the bridge by 2030.', "won't have built", ["won't build", "don't build", "haven't built"], 'Phủ định: won\'t have + V3.', ['will not have built']],
    [1, '___ (you / complete) the course by then?', 'Will you have completed', ['Will you complete', 'Do you complete', 'Have you completed'], 'Câu hỏi: Will + S + have + V3?'],
    [1, 'In two years\' time, he ___ (pay) off his loan.', 'will have paid', ['will pay', 'pays', 'has paid'], 'Hoàn tất trước một thời điểm tương lai.'],
    [2, 'By the end of this year, I ___ (read) 50 books.', 'will have read', ['will read', 'read', 'am reading'], 'Kết quả đạt được trước mốc tương lai.'],
    [2, 'The film ___ (already / start) by the time we get to the cinema.', 'will have already started', ['will already start', 'already starts', 'has already started'], '"already" giữa will have và V3.'],
    [2, 'Next month, we ___ (be) married for ten years.', 'will have been', ['are', 'will be', 'have been'], 'Đến tháng sau sẽ tròn 10 năm → TLHT.'],
    [2, 'Hurry up! By the time we arrive, everyone ___ (leave).', 'will have left', ['leaves', 'will leave', 'has left'], 'Hoàn thành trước lúc chúng ta đến.'],
    [2, 'She ___ (not / save) enough money by next summer to buy a car.', "won't have saved", ["won't save", "doesn't save", "hasn't saved"], 'Phủ định TLHT.', ['will not have saved']],
    [2, 'How many countries ___ (you / visit) by the time you are 30?', 'will you have visited', ['will you visit', 'do you visit', 'have you visited'], 'Hỏi kết quả đạt được trước mốc tương lai.'],
    [3, 'When she ___ (retire) next year, she ___ (work) here for 40 years.', 'retires / will have worked', ['will retire / will work', 'retires / works', 'will retire / will have worked'], 'Mệnh đề thời gian HTĐ; kết quả tích luỹ đến mốc đó → TLHT.', ['retires / will have been working']],
    [3, 'Câu nào đúng ngữ pháp?', 'By the time the guests arrive, I will have cooked everything.', ['By the time the guests will arrive, I will have cooked everything.', 'By the time the guests arrive, I will cook everything.', 'By the time the guests arrived, I will have cooked everything.'], 'By the time + HTĐ, TLHT.', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'I will have finished the project before the deadline.', ['I will finished the project before the deadline.', 'I have finished the project before the deadline will come.', 'I will have finish the project before the deadline.'], 'will have + V3.', [], 'pick'],
    [3, 'Don\'t worry about the report. I ___ (send) it by the time you ___ (arrive) tomorrow.', 'will have sent / arrive', ['will send / will arrive', 'send / arrive', 'will have sent / will arrive'], 'TLHT + mệnh đề thời gian HTĐ.'],
    [3, 'By 2040, scientists ___ (probably / find) a cure for the disease.', 'will probably have found', ['probably will find', 'will have probably find', 'probably find'], 'Trạng từ "probably" đứng sau will: will probably have + V3.', ['will have probably found']],
    [3, 'Câu nào đúng ngữ pháp?', 'She won\'t have arrived by nine, so let\'s start without her.', ['She won\'t arrive by nine, so let\'s start without her.', 'She won\'t have arrive by nine, so let\'s start without her.', 'She hasn\'t arrived by nine, so let\'s start without her.'], 'Phủ định TLHT: won\'t have + V3.', [], 'pick'],
  ],
  fpc: [
    [1, 'By next month, I ___ (work) here for five years.', 'will have been working', ['will work', 'work', 'have worked'], '"By + mốc tương lai + for" → will have been + V-ing.'],
    [1, 'By 2030, she ___ (teach) for 20 years.', 'will have been teaching', ['will teach', 'teaches', 'has taught'], 'Nhấn mạnh thời lượng đến mốc tương lai.'],
    [1, 'By the time you arrive, we ___ (wait) for two hours.', 'will have been waiting', ['will wait', 'wait', 'are waiting'], 'By the time + HTĐ, TLHTTD.'],
    [1, 'He ___ (not / live) here long by then.', "won't have been living", ["won't live", "doesn't live", "isn't living"], 'Phủ định: won\'t have been + V-ing.', ['will not have been living']],
    [1, '___ (you / study) English for ten years by next year?', 'Will you have been studying', ['Will you study', 'Do you study', 'Have you studied'], 'Câu hỏi: Will + S + have been + V-ing?'],
    [1, 'By midnight, the band ___ (play) for six hours.', 'will have been playing', ['plays', 'will play', 'has played'], 'Thời lượng liên tục đến mốc tương lai.'],
    [2, 'At the end of this year, they ___ (build) the road for 18 months.', 'will have been building', ['will build', 'have built', 'are building'], 'Nhấn quá trình kéo dài (chưa chắc xong).'],
    [2, 'By the time the meeting ends, we ___ (discuss) the budget for three hours.', 'will have been discussing', ['discuss', 'will discuss', 'have discussed'], 'By the time + HTĐ, TLHTTD.'],
    [2, 'Next week, I ___ (learn) to drive for a month and I still can\'t park!', 'will have been learning', ['will learn', 'learn', 'am learning'], 'Thời lượng đến mốc tương lai + vẫn tiếp diễn.'],
    [2, 'When he retires, he ___ (run) the company for 25 years.', 'will have been running', ['runs', 'will run', 'has run'], 'Mệnh đề thời gian HTĐ + TLHTTD.'],
    [2, 'By tomorrow morning, it ___ (rain) for 48 hours.', 'will have been raining', ['will rain', 'rains', 'is raining'], 'Mưa liên tục đến sáng mai.'],
    [2, 'How long ___ (she / wait) by the time the doctor sees her?', 'will she have been waiting', ['will she wait', 'does she wait', 'has she waited'], 'Hỏi thời lượng đến mốc tương lai.'],
    [3, 'By Friday, she ___ (write) the thesis for a year and she ___ (write) 200 pages.', 'will have been writing / will have written', ['will have written / will have been writing', 'will write / will have written', 'writes / has written'], 'Quá trình → TLHTTD; kết quả đếm được → TLHT.'],
    [3, 'Câu nào đúng ngữ pháp?', 'By June, I will have known him for exactly ten years.', ['By June, I will have been knowing him for exactly ten years.', 'By June, I will know him for exactly ten years.', 'By June, I have known him for exactly ten years.'], '"know" trạng thái → TLHT, không dùng tiếp diễn.', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'When you get back, I will have been working for 12 hours straight.', ['When you will get back, I will have been working for 12 hours straight.', 'When you get back, I will been working for 12 hours straight.', 'When you get back, I will have working for 12 hours straight.'], 'Mệnh đề thời gian HTĐ; will have been + V-ing.', [], 'pick'],
    [3, 'He\'ll be exhausted when he finishes – he ___ (drive) for nine hours.', 'will have been driving', ['will drive', 'drives', 'has been driving'], 'Nguyên nhân dự kiến của tình trạng tương lai → TLHTTD.'],
    [3, 'By the time the project ___ (end), the team ___ (work) on it for two years.', 'ends / will have been working', ['will end / will have been working', 'ends / works', 'will end / has been working'], 'By the time + HTĐ; thời lượng → TLHTTD.'],
    [3, 'Câu nào đúng ngữ pháp?', 'Will they have been living together for a year by then?', ['Will they have living together for a year by then?', 'Have they been living together for a year by then?', 'Will they be living together for a year by then?'], 'Will + S + have been + V-ing?', [], 'pick'],
  ],
  nf: [
    [1, 'We ___ (visit) Hue next month. We\'ve already booked the hotel.', 'are going to visit', ['will visit', 'visit', 'visited'], 'Kế hoạch có trước (đã đặt phòng) → be going to.'],
    [1, 'Look at those clouds! It ___ (rain).', 'is going to rain', ['will rain', 'rains', 'rained'], 'Dự đoán có bằng chứng → be going to.'],
    [1, 'I ___ (study) medicine at university.', 'am going to study', ['will study', 'study', 'am study'], 'Dự định → am going to.'],
    [1, 'They ___ (not / buy) that house. It\'s too expensive.', "aren't going to buy", ["won't going to buy", "don't going to buy", "aren't buy"], 'Phủ định: be + not + going to + V.', ['are not going to buy']],
    [1, '___ (you / tell) him the truth?', 'Are you going to tell', ['Do you going to tell', 'Will you going to tell', 'Are you going tell'], 'Câu hỏi: Are + S + going to + V?'],
    [1, 'Be careful! You ___ (fall).', 'are going to fall', ['will fall', 'fall', 'are falling'], 'Sắp xảy ra dựa trên tình huống trước mắt.'],
    [2, 'She has bought a lot of flour. She ___ (bake) a cake.', 'is going to bake', ['will bake', 'bakes', 'is baking'], 'Kế hoạch có dấu hiệu rõ (đã mua bột).'],
    [2, 'What ___ (you / do) after you graduate?', 'are you going to do', ['will you do', 'do you do', 'you are going to do'], 'Hỏi dự định → be going to.'],
    [2, 'I ___ (not / work) this weekend. I need a rest.', "am not going to work", ["won't going to work", "am not work", "don't going to work"], 'Phủ định với "I": am not going to.', ["'m not going to work"]],
    [2, 'The company ___ (open) a new branch in Da Nang next year – they announced it last week.', 'is going to open', ['opens', 'will open', 'is opening'], 'Kế hoạch đã công bố → be going to.'],
    [2, 'He is driving so fast. He ___ (have) an accident!', 'is going to have', ['will have', 'has', 'is having'], 'Dự đoán từ tình huống hiện tại.'],
    [2, 'A: Why are you wearing running shoes? B: I ___ (go) jogging.', 'am going to go', ['will go', 'go', 'went'], 'Dự định rõ ràng (đã mang giày).', ['am going']],
    [3, 'A: We\'re out of milk. B: Really? I ___ (get) some from the shop. – A: No need, I ___ (go) shopping anyway, I made a list this morning.', 'will get / am going to go', ['am going to get / will go', 'will get / will go', 'am going to get / am going to go'], 'Quyết định tức thời → will; kế hoạch có trước (đã lên danh sách) → be going to.', ['will get / am going']],
    [3, 'Câu nào đúng ngữ pháp?', 'I\'m going to see the dentist tomorrow – I made the appointment last week.', ['I will see the dentist tomorrow – I made the appointment last week.', 'I see the dentist tomorrow – I made the appointment last week.', 'I\'m going to seeing the dentist tomorrow – I made the appointment last week.'], 'Kế hoạch đã sắp xếp → be going to + V nguyên mẫu.', [], 'pick'],
    [3, 'Câu nào đúng ngữ pháp?', 'Watch out! That glass is going to fall!', ['Watch out! That glass will fall!', 'Watch out! That glass falls!', 'Watch out! That glass going to fall!'], 'Dự đoán dựa trên bằng chứng ngay trước mắt → be going to.', [], 'pick'],
    [3, 'I think she ___ (like) the gift, but she ___ (not / open) it until her birthday – that\'s her rule.', "will like / isn't going to open", ["is going to like / won't open", "likes / doesn't open", "will like / doesn't open"], 'Dự đoán chủ quan (I think) → will; dự định/nguyên tắc có trước → be going to.', ['will like / is not going to open']],
    [3, 'Câu nào đúng ngữ pháp?', 'Are you going to apply for the job?', ['Do you going to apply for the job?', 'Are you go to apply for the job?', 'Will you going to apply for the job?'], 'Are + S + going to + V?', [], 'pick'],
    [3, 'The sky is getting dark and the wind is picking up. There ___ (be) a storm.', 'is going to be', ['will be', 'is', 'was'], 'Dự đoán từ dấu hiệu hiện tại → be going to.'],
  ],
};

/** Danh sách câu soạn tay của một thì theo mức, đã chuẩn hoá về dạng { tense, lv, kind, q, a, alts, opts, x } */
export function bankQuestions(tense, lv) {
  return (B[tense] || []).filter(it => it[0] === lv).map(it => {
    const [, q, a, wrong, x, alts = [], kind] = it;
    return { tense, lv, kind: kind === 'pick' ? 'pick' : 'mc', q, a, alts, opts: [a, ...wrong], x, gen: false };
  });
}
export const BANK_COUNT = Object.fromEntries(Object.entries(B).map(([k, v]) => [k, v.length]));
